# Generated by Django 5.2.17 on 2026-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_harden_web_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrunstate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('processing', 'Processing'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
